version: '3.3'

volumes:
  postgres_data: {}
  sna_data: {}

services:
  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    env_file: .env
    networks:
      - sna-net

  redis:
    ports:
      - "6379:6379"
    image: 'redis:alpine'
    networks:
      - sna-net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
    networks:
      - sna-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
    logging:
      driver: none
    networks:
      - sna-net

networks:
  sna-net:
    driver: bridge
