# Generated by Django 4.2 on 2023-05-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='P', max_length=1)),
                ('friend_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_a_set', to=settings.AUTH_USER_MODEL, verbose_name='Addressee')),
                ('friend_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_r_set', to=settings.AUTH_USER_MODEL, verbose_name='Requestor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
